upstream app {
	server app:3000;
}

server {
	listen 80 default_server;
	root /web;

	auth_basic "Admin Area";
	auth_basic_user_file .htpasswd;

	location /graphql {
		auth_basic off;
	}

	location / {
		include security_headers.conf;
		proxy_intercept_errors on;
		proxy_pass http://app;
	}
}
