version: '3.2'

services:
  tests:
    image: cirunner
    build:
      context: ..
      dockerfile: deployment/cirunner/Dockerfile
      cache_from:
        - 'ghcr.io/${GITHUB_REPOSITORY}/cirunner-cache'
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: ['exit']
    user: $USER
    volumes:
      - $PWD:/app
